import { MultiDocAnalysis } from '../types/contract';

export function generateMarkdownReport(analysis: MultiDocAnalysis): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `# CONTRACTGUARD AI: AUDIT & COMPLIANCE INTELLIGENCE REPORT
**Generated:** ${dateStr}
**Analysis Scope:** ${analysis.title}
**Overall Risk Assessment:** ${analysis.overallRiskLevel} (Compliance Score: ${analysis.complianceScore}/100)

---

> **LEGAL NOTICE & DISCLAIMER:**
> This report is generated by ContractGuard AI for informational and compliance screening purposes only. It does not constitute formal legal advice, representation, or an attorney-client relationship. Qualified legal counsel should review all findings prior to agreement execution.

---

## 1. EXECUTIVE SUMMARY

### Professional Legal Summary:
${analysis.executiveSummary}

### Simple Plain-English Summary (Non-Expert Overview):
${analysis.simpleSummary}

---

## 2. DOCUMENT OVERVIEW (${analysis.documents.length} Document${analysis.documents.length > 1 ? 's' : ''} Analyzed)

| Document Name | Classification | Estimated Pages | File Size |
| :--- | :--- | :--- | :--- |
${analysis.documents.map(d => `| **${d.name}** | ${d.docType} | ${d.pageCount} pages | ${(d.sizeBytes / 1024).toFixed(1)} KB |`).join('\n')}

---

## 3. RISK AUDIT DASHBOARD METRICS

- **Total Risks Identified:** ${analysis.totalRisks}
  - 🔴 **High / Critical Risks:** ${analysis.highRisks}
  - 🟡 **Medium Risks:** ${analysis.mediumRisks}
  - 🟢 **Low Risks:** ${analysis.lowRisks}
- **Compliance Gaps Detected:** ${analysis.complianceGapsCount}
- **Critical Obligations Monitored:** ${analysis.importantObligationsCount}
- **Upcoming Deadlines & Milestones:** ${analysis.upcomingDeadlinesCount}

---

## 4. DETAILED RISK FINDINGS & ATTRIBUTION

${analysis.risks.map((risk, index) => `
### Finding #${index + 1}: [${risk.level}] ${risk.issue}
- **Document Source:** \`${risk.docName}\`
- **Clause / Section:** ${risk.clauseOrSection}
- **Page Reference:** ${risk.pageNumber ? `Page ${risk.pageNumber}` : 'Document Body'}
- **Risk Category:** ${risk.category}
- **Why It Matters:** ${risk.whyItMatters}
- **Simple Explanation:** ${risk.simpleExplanation || 'Plain language breakdown provided in dashboard.'}
- **Recommended Counter-Proposal / Action:** 
  > *${risk.suggestedAction}*
`).join('\n---\n')}

---

${analysis.comparison && analysis.comparison.conflicts.length > 0 ? `
## 5. CROSS-DOCUMENT COMPARISON & CONFLICTING CLAUSES

The following direct clause conflicts were discovered across the uploaded documents:

${analysis.comparison.conflicts.map((c, i) => `
### Conflict #${i + 1}: ${c.topic} [Severity: ${c.severity}]
- **Document A (\`${c.docAName}\`):** 
  > "${c.docAClause}" ${c.docAPage ? `*(Page ${c.docAPage})*` : ''}
- **Document B (\`${c.docBName}\`):** 
  > "${c.docBClause}" ${c.docBPage ? `*(Page ${c.docBPage})*` : ''}
- **Conflict Analysis:** ${c.conflictSummary}
- **Recommended Alignment Action:** ${c.resolutionGuidance}
`).join('\n---\n')}
` : ''}

${analysis.comparison && analysis.comparison.complianceGaps.length > 0 ? `
## 6. COMPLIANCE GAPS & POLICY VIOLATIONS

${analysis.comparison.complianceGaps.map((gap, i) => `
${i + 1}. **${gap.ruleOrPolicy}** [${gap.severity}]
   - **Target Document:** \`${gap.targetDoc}\`
   - **Finding:** ${gap.finding}
   - **Remediation:** ${gap.recommendation}
`).join('\n')}
` : ''}

---

## 7. KEY OBLIGATIONS MATRIX

| Document | Obligated Party | Section | Type | Description | Criticality |
| :--- | :--- | :--- | :--- | :--- | :--- |
${analysis.obligations.map(ob => `| \`${ob.docName}\` | **${ob.party}** | ${ob.section} | ${ob.type.toUpperCase()} | ${ob.description} | ${ob.isCritical ? '⚠️ CRITICAL' : 'Standard'} |`).join('\n')}

---

## 8. UPCOMING DEADLINES & TIMELINES

| Document | Event / Milestone | Due Date | Priority | Details |
| :--- | :--- | :--- | :--- | :--- |
${analysis.deadlines.map(dl => `| \`${dl.docName}\` | **${dl.title}** | ${dl.dueDate} | ${dl.priority} | ${dl.description} |`).join('\n')}

---

## 9. AREAS REQUIRING HUMAN LEGAL REVIEW

1. **Unilateral Indemnity & Liability Caps:** Mandate reciprocal liability limits tied to annual contract value.
2. **Breach Notification Timelines:** Align incident reporting with statutory 72-hour GDPR standards.
3. **Data Usage & AI Training:** Explicitly strike any clauses allowing counterparty to utilize proprietary data for model training.
4. **Dispute Resolution & Jurisdiction:** Confirm venue alignment with company counsel guidelines.

---
*Report generated by ContractGuard AI — Autonomous Contract & Compliance Intelligence System.*
`;
}

export function downloadMarkdownReport(analysis: MultiDocAnalysis) {
  const content = generateMarkdownReport(analysis);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `ContractGuard_Audit_Report_${Date.now()}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printHtmlReport(analysis: MultiDocAnalysis) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow pop-ups to generate and print the report.');
    return;
  }

  const markdown = generateMarkdownReport(analysis);
  // Simple HTML converter for print
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <title>ContractGuard AI - Audit Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      max-width: 900px;
      margin: 40px auto;
      padding: 0 20px;
    }
    h1 { color: #312e81; border-bottom: 2px solid #6366f1; padding-bottom: 8px; font-size: 24px; }
    h2 { color: #1e1b4b; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; margin-top: 30px; font-size: 18px; }
    h3 { color: #4338ca; font-size: 15px; margin-top: 20px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 13px; }
    th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
    th { background-color: #f1f5f9; color: #0f172a; font-weight: 600; }
    blockquote { border-left: 3px solid #6366f1; margin: 10px 0; padding: 8px 15px; background: #f8fafc; font-style: italic; color: #334155; }
    .badge-high { color: #dc2626; font-weight: bold; }
    .badge-med { color: #d97706; font-weight: bold; }
    .badge-low { color: #16a34a; font-weight: bold; }
    .disclaimer { background: #fef3c7; border: 1px solid #f59e0b; padding: 12px; border-radius: 6px; font-size: 12px; color: #92400e; margin: 20px 0; }
    @media print {
      body { margin: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom: 20px; text-align: right;">
    <button onclick="window.print()" style="background: #4f46e5; color: white; border: none; padding: 10px 20px; border-radius: 6px; cursor: pointer; font-weight: bold;">
      Print / Save as PDF
    </button>
  </div>
  <div class="disclaimer">
    <strong>Legal Notice:</strong> This report is AI-assisted and provided for informational screening purposes only. It does not replace qualified professional legal or compliance advice.
  </div>
  <pre style="white-space: pre-wrap; font-family: inherit;">${markdown.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
</body>
</html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
