import React from 'react';
import { FileText, Download, Printer, X, ShieldAlert, CheckCircle, AlertTriangle } from 'lucide-react';
import { MultiDocAnalysis } from '../types/contract';
import { downloadMarkdownReport, printHtmlReport, generateMarkdownReport } from '../services/reportService';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: MultiDocAnalysis;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  analysis,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-4xl max-h-[90vh] flex flex-col rounded-3xl glass-panel border border-slate-700 bg-slate-900/95 shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-slate-900/90">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-black text-white">
                Contract & Compliance Intelligence Audit Report
              </h3>
              <p className="text-xs text-slate-400">
                Formal legal audit summary ready for human review and executive export
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => printHtmlReport(analysis)}
              className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold flex items-center gap-1.5 shadow-md shadow-indigo-600/30 transition-all"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Save as PDF</span>
            </button>

            <button
              onClick={() => downloadMarkdownReport(analysis)}
              className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-200 text-xs font-bold flex items-center gap-1.5 transition-all"
            >
              <Download className="w-4 h-4" />
              <span>Download (.md)</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Content Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 text-slate-200 font-sans text-xs sm:text-sm">
          {/* Disclaimer Alert */}
          <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-300 text-xs flex items-center gap-2.5">
            <AlertTriangle className="w-4 h-4 flex-shrink-0 text-amber-400" />
            <span>
              <strong>Legal Notice:</strong> This audit report is AI-assisted and generated for informational screening purposes. It does not replace formal legal counsel or compliance sign-off.
            </span>
          </div>

          {/* Report Preview */}
          <div className="p-6 rounded-2xl bg-slate-950/80 border border-slate-800 space-y-5">
            {/* Header info */}
            <div>
              <h2 className="text-xl font-black text-white">{analysis.title}</h2>
              <p className="text-xs text-slate-400 mt-1">
                Generated by ContractGuard AI • Overall Risk: <strong className="text-rose-400">{analysis.overallRiskLevel}</strong> • Compliance Score: <strong className="text-indigo-400">{analysis.complianceScore}/100</strong>
              </p>
            </div>

            {/* Document Overview */}
            <div className="space-y-2 pt-2 border-t border-slate-800">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400">
                1. Analyzed Documents ({analysis.documents.length})
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                {analysis.documents.map((d) => (
                  <div key={d.id} className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
                    <div className="font-bold text-slate-200">{d.name}</div>
                    <div className="text-[11px] text-slate-400">
                      {d.docType} • {d.pageCount} pages • {(d.sizeBytes / 1024).toFixed(1)} KB
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Executive Summary */}
            <div className="space-y-1.5 pt-2 border-t border-slate-800">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400">
                2. Executive Summary
              </h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                {analysis.executiveSummary}
              </p>
            </div>

            {/* Risk Findings Table */}
            <div className="space-y-2 pt-2 border-t border-slate-800">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400">
                3. Risk Findings ({analysis.risks.length})
              </h3>
              <div className="space-y-2">
                {analysis.risks.map((r, idx) => (
                  <div key={r.id || idx} className="p-3 rounded-lg bg-slate-900/60 border border-slate-800 text-xs space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-slate-100">
                        {idx + 1}. {r.issue}
                      </span>
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        r.level === 'HIGH' ? 'bg-rose-500/20 text-rose-300' : 'bg-amber-500/20 text-amber-300'
                      }`}>
                        {r.level} RISK
                      </span>
                    </div>
                    <div className="text-[11px] text-slate-400">
                      Source: <code className="text-indigo-300 font-mono">{r.docName}</code> ({r.clauseOrSection}{r.pageNumber ? `, Page ${r.pageNumber}` : ''})
                    </div>
                    <p className="text-slate-300 text-[11px]">
                      <strong>Impact:</strong> {r.whyItMatters}
                    </p>
                    <p className="text-emerald-300 text-[11px]">
                      <strong>Recommended Action:</strong> {r.suggestedAction}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Conflicts if multiple docs */}
            {analysis.comparison && analysis.comparison.conflicts.length > 0 && (
              <div className="space-y-2 pt-2 border-t border-slate-800">
                <h3 className="text-xs font-bold uppercase tracking-wider text-rose-400">
                  4. Conflicting Clauses ({analysis.comparison.conflicts.length})
                </h3>
                <div className="space-y-2">
                  {analysis.comparison.conflicts.map((c, idx) => (
                    <div key={c.id || idx} className="p-3 rounded-lg bg-rose-950/20 border border-rose-800/40 text-xs space-y-1">
                      <span className="font-bold text-rose-300">{c.topic}</span>
                      <p className="text-slate-300 text-[11px]">{c.conflictSummary}</p>
                      <p className="text-indigo-300 text-[11px]">
                        <strong>Resolution:</strong> {c.resolutionGuidance}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-900/90 flex items-center justify-between text-xs text-slate-400">
          <span>Ready for executive signature and redline distribution</span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 hover:text-white font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
